# Setup:
#   mkdir -p ~/.config/alacritty/themes
#   git clone https://github.com/alacritty/alacritty-theme ~/.config/alacritty/themes/

[general]
import = [
    "~/.config/alacritty/themes/themes/selenized_dark.toml"
]
